name: kaspi_clone
description: Kaspi Bank Clone
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.4
  local_auth: ^2.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  nfc_manager: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
