name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Remove broken android folder
        run: rm -rf android

      - name: Recreate Android project
        run: flutter create --platforms=android .

      - name: Fix SDK and Give Enough Heap Space
        run: |
          cat << 'EOF' >> android/build.gradle
          subprojects {
              afterEvaluate {
                  if (plugins.hasPlugin('com.android.application') || plugins.hasPlugin('com.android.library')) {
                      android {
                          compileSdkVersion 36
                          defaultConfig {
                              minSdkVersion 24
                          }
                      }
                  }
              }
          }
          EOF
          
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          # Выделяем 4 ГБ памяти, чтобы Jetifier не падал по Java heap space
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8" >> android/gradle.properties
          echo "org.gradle.parallel=true" >> android/gradle.properties
          echo "kotlin.daemon.jvm.options=-Xmx2048m" >> android/gradle.properties

      - name: Install Android SDK 36 Platform
        run: |
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-36" || true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
